### ISSUE TITLE
Way too many departments!

### ISSUE THREAD

**Issue by RobRuana** [magfest/magwest#10]
As reported by Ryan on Slack

> Some of these departments need to be trimmed out, as they're not all relevant to West...

![2017-04-20_1559](https://cloud.githubusercontent.com/assets/2592431/25256447/b98eed94-25fe-11e7-9511-9b4d3cd4ce44.png)

Which is weird, because I definitely didn't notice this before ☹️

**Comment by ShevaDas** [comment]
Departments we can remove (+1 from @migetman9 would be good):

* Autographs
* Challenges
* Escape Room
* Events? (I don't know what this is)
* Games on Film
* LARP
* MAGES
* MAGFest Grand Championship
* Museum
* Public Safety (I don't know what the distinction between this and Dorsai and Security is)
* Security (see above)
* Simulations
* Staff Suite
* Tabletop (CCG)
* Tabletop (DDAL)
* Tabletop (Pathfinder)
* Yetee Staff
* Zombie Tag

**Comment by migetman9** [comment]
Yes to all but Security. I believe it represents Concert Security.

**Comment by RobRuana** [comment]
I should mention @migetman9 and @ShevaDas, there are a bunch of other MAGPrime specific things  besides departments in https://github.com/magfest/production-config/blob/master/event-west.yaml

**Comment by migetman9** [comment]
I was afraid of moving things like the peglegs signature as I've learned first hand that removing bits of the config can randomly crash entire pages.

**Comment by RobRuana** [comment]
Cool cool, as long as your aware of it :)

**Comment by migetman9** [comment]
Example: If I remove uber::config::dept_head_overrides: because we aren't using it. Will it cause an email or staff page to say its missing a config variable?

I'm happy to start removing that stuff, if and only if you're down to smack the bugs as they pop up. :)

**Comment by RobRuana** [comment]
I'd leave that kind of stuff until it becomes an issue. But, I am serving at your discretion, so I'm up for whatever helps you out the most!

**Comment by migetman9** [comment]
Leave it until it becomes an issue!
