### ISSUE TITLE
magconfig: returning staff email text should get changed

### ISSUE THREAD

**Issue by binary1230** [magfest/magwest#12]
https://github.com/magfest/magwest/blob/master/magwest/templates/emails/placeholders/imported_volunteer.txt

- should be edited to remove references to 'thanks for helping last year' and such.
- should be reviewed by STOPs dept for policy accuracy regarding hotel rooms

-----

actually: i'd say LOW PRIORITY since we don't have any staff that are imported for west, and only Dom and RobR got these emails, being the only staffers that existed prior to prereg being opened.

**Comment by RobRuana** [comment]
As far as I can tell, this is how that email is actually being created:

```python
StopsEmail('Want to staff {EVENT_NAME} again?', 'placeholders/imported_volunteer.txt',
           lambda a: a.placeholder and a.staffing and a.registered_local <= c.PREREG_OPEN,
           ident='volunteer_again_inquiry')
```

Which basically means (as you described) only staffers whose `registered_local` date is BEFORE `PREREG_OPEN` will receive the email. So this will be relevant for MAGWest 2018 (Whoo Hoo!) but not this year, correct?

**Comment by kitsuta** [comment]
Yup. I also see no reason to take the 'thanks for helping last year' text out, since this email is designed to only go to staffers that would have helped a prior year.
