### ISSUE TITLE
magconfig: push back volunteer checklist date

### ISSUE THREAD

**Issue by binary1230** [magfest/magwest#13]
email with subject line:
Please complete your MAGWest Staff/Volunteer Checklist

1) these emails are currently being generated because the date in production-config is set to March 1st, we should push that date back to like June 1st to give some breathing room.   

2) We may want to delete the currently generated emails for this ident that exist in the DB which might not be accurate in a month or so because people's dept assignments will have changed. (emails are generated and queued if the date condition is true, but don't go out until they are explicitly approved, which hasn't happened yet for magwest [good thing])

low priority for right now, since these emails are not marked approved and aren't sending

**Comment by RobRuana** [comment]
To confirm, I believe this is the email template you are referring to:
https://github.com/magfest/magwest/blob/master/magwest/templates/emails/shifts/created.txt

And some amplifying info for anyone happening across this issue, the email is defined here:
https://github.com/magfest/ubersystem/blob/master/uber/automated_emails.py#L464

And (as of this comment) looks like this:
```python
StopsEmail('Please complete your {EVENT_NAME} Staff/Volunteer Checklist', 'shifts/created.txt',
           lambda a: a.takes_shifts,
           when=days_after(0, c.SHIFTS_CREATED),
           ident='volunteer_checklist_completion_request')
```

So, the relevant config setting is `uber::config::shifts_created` as found here:
https://github.com/magfest/production-config/blob/master/event-west.yaml#L57

**Comment by RobRuana** [comment]
1. Should be fixed by https://github.com/magfest/production-config/pull/206
2. By "delete in the DB" do you mean deleting them via psql?

**Comment by kitsuta** [comment]
Yeah, we'll need to delete them in the DB manually on the prod server.

**Comment by RobRuana** [comment]
Was closed automatically by the pull request, but really we still need to delete the existing emails in the DB (which sounds a little dicey IMHO).

**Comment by kitsuta** [comment]
You're, uh, not wrong. But we do have a unique ident column now so that should make things a bit less dicey.

**Comment by RobRuana** [comment]
Ah hah! I have just checked in the production DB server, and the referenced emails have NOT yet been created in the DB!

Thus, I am closing this issue as done!
