### ISSUE TITLE
Volunteer Checklist lists Dietary Preference - Does not apply for this year

### ISSUE THREAD

**Issue by ryanrcho** [magfest/magwest#20]
Repro:
1.  Log into the Volunteer Checklist via the following link (https://west2017.uber.magfest.org/uber/signups/login)

Result:
The West 2017 Volunteer Checklist lists dietary restrictions for this year, stating that "Volunteers who have met hour requirements for food will be served 3 meals a day and have access to staff suite 24 hours a day!"
![2017-07-09_1201](https://user-images.githubusercontent.com/27836529/27996767-61800140-649e-11e7-8c56-1db8ec175a3d.png)

Expected Result:
As per Sheva, we are NOT feeding staff and volunteers this year so this needs to be removed from the checklist.

**Comment by outlaw-josiah** [comment]
This might also be relevant to the Labs uber, as they are also not feeding staff this year. However, the volunteer checklist isn't live, so I can't confirm that.

**Comment by RobRuana** [comment]
Good to know! We'll get on it!

**Comment by RobRuana** [comment]
FYI, the fix in this [pull request](https://github.com/magfest/ubersystem/pull/2628) will also work labs.

**Comment by kitsuta** [comment]
Labs already has the food step removed in config, so they should be good. :)

**Comment by kitsuta** [comment]
Fixed in https://github.com/magfest/production-config/pull/232.
