### ISSUE TITLE
Replace references to MAGLabs in MAGWest emails

### ISSUE THREAD

**Issue by dlenik** [magfest/magwest#21]
For example, look at "MAGWest FAQ" in Uber (https://west2017.uber.magfest.org/uber/emails/pending_examples?ident=magwest_prefest_faq).

**Comment by RobRuana** [comment]
Whoops! There's also still references to the Mark Center on Seminary Road...

**Comment by kitsuta** [comment]
I figure that's a separate issue. The text is typically reviewed and
altered close to the event.

**Comment by RobRuana** [comment]
Also references to the wrong guidebook, bad parking instructions, etc... the whole thing really needs to be updated. The entirety of this file needs to be reviewed: https://github.com/magfest/magwest/blob/master/magwest/templates/emails/prefest_faq.html

I am going to assign this issue to @migetman9 and @ShevaDas!
