### ISSUE TITLE
MAGWest's extra JS to hide amount_extra is breaking the admin form in some cases

### ISSUE THREAD

**Issue by kitsuta** [magfest/magwest#27]
Sometimes when editing a badge in MAGWest, a JS error comes up:
`Uncaught TypeError: Cannot read property 'parents' of null`
About this block:
```
    <script type="text/javascript">
        $.field('amount_extra').parents('.form-group').hide();
    </script>
```

However, that block is behind a `{% if c.PAGE_PATH != 'registration/form' %}` -- it shouldn't even be rendering this script.

The JS error breaks other JS on the page; most notably, it prevents admins from deleting a badge (it simply says "This attendee has been saved" when you try).

**Comment by RobRuana** [comment]
I'm guessing that `c.PAGE_PATH` starts with a slash, so that should be:
```python
{% if c.PAGE_PATH != '/registration/form' %}
```

**Comment by kitsuta** [comment]
True! Probably even better though would be to use our `admin_area` var.
