### ISSUE TITLE
Aracde DH does not Appear in the DH Checklist

### ISSUE THREAD

**Issue by ryanrcho** [magfest/magwest#29]
I've found an odd quirk in Uber-W where one of the DHs for Arcade isn't showing up in the department checklist, even though other departments have multiple heads.

**Comment by kitsuta** [comment]
This individual used to be a department head in two departments (Arcade and Arcade Crew), until we removed one of those departments from config.

This made it LOOK like they were a department head with only one department, but in the database, they would still have two values, making them fail the `single_dept_heads` query.

I resolved this by re-saving the attendee. They're now in the overview list, and should also be able to actually access the dept head checklist. Please let them know!
