### ISSUE TITLE
Email Sent Out to Volunteers have old info on it

### ISSUE THREAD

**Issue by ryanrcho** [magfest/magwest#30]
Heyo,

A volunteer messaged me confused about the deadline on the emails.

Apparently, the deadline for volunteers to sign up for shifts is set to " 11:59pm on Sunday, September 4th."

It also contains "- Any food restrictions you might have for our Staff Suite", which is not happening for this year.

I'm currently working on figuring out the correct dates for the volunteer deadline.  I'll update the ticket when I get that info.

**Comment by RobRuana** [comment]
Cool, add the dates in a comment, and we'll be notified as soon as you post it!

**Comment by ryanrcho** [comment]
Bah - the email's already sent out so the damage is done.  I'll have to look at getting a list of the people the email's been sent out to and possibly re-send a correction instead... is that possible to gather?  The email list sent out was the "Please complete your MAGWest Staff/Volunteer Checklist" email.
