### ISSUE TITLE
Change techops requirements link on west uber

### ISSUE THREAD

**Issue by ryanrcho** [magfest/magwest#31]
As per Ted within JIRA:

https://docs.google.com/a/magwest.org/forms/d/e/1FAIpQLSeU1VK-i9O6L_WuYEaascBPl01knVGSNvkimEEFJKbZHejjwA/viewform?usp=sf_link

is the form I'm using. I don't have access to the form that is linked.

**Comment by ryanrcho** [comment]
Ted made the ticket within JIRA 5 days ago but I don't think anyone saw it in there.  Making this ticket JUST IN CASE.

**Comment by RobRuana** [comment]
Already done!

https://github.com/magfest/production-config/commit/0e337d4d1c7fb629d49aef9604827bca86539108
