### ISSUE TITLE
Review dates in west config files

### ISSUE THREAD

**Issue by RobRuana** [magfest/magwest#7]
Note: this issue actually concerns the https://github.com/magfest/production-config repo, but I'm adding it here to group it under the https://github.com/magfest/magwest/projects/1 rollout.

Specifically there are a bunch of dates in https://github.com/magfest/production-config/blob/master/event-west.yaml

**Comment by BlueHat-GURU** [comment]
@binary1230 @migetman9 @ShevaDas

**Comment by RobRuana** [comment]
The only blocking change is the pre reg opening date:
```
uber::config::prereg_open: '2017-06-30 16'
```

*I think* we can push the other dates way off into the future until we decide on the correct dates, but if we can figure out good approximations of everything now, that would be great.

**Comment by RobRuana** [comment]
Closed by https://github.com/magfest/production-config/pull/201
